apiVersion: v1
data:
  database-name: cmVjaXBldmF1bHRkYg==
  database-password: cmVjaXBldmF1bHQ=
  database-user: cmVjaXBldmF1bHQ=
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: postgresql-persistent
    app.kubernetes.io/component: postgresql-persistent
    app.kubernetes.io/instance: postgresql-persistent
    template: postgresql-persistent-template
  name: postgresql
type: Opaque
