apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipevault-frontend
  labels:
    app: recipevault-frontend
    app.kubernetes.io/component: recipevault-frontend
    app.kubernetes.io/instance: recipevault-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: recipevault-frontend
  template:
    metadata:
       labels:
        deployment: recipevault-frontend
    spec:
      volumes:
        - name: recipevault-pvc
          persistentVolumeClaim:
            claimName: recipevault-pvc
      containers:
        - name: recipevault-frontend
          image: >-
            quay.io/geoallen/recipevault-frontend:stage
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: recipevault-pvc
              mountPath: /opt/app-root/src/images
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
