kind: Service
apiVersion: v1
metadata:
  name: recipevault-frontend
  labels:
    app: recipevault-frontend
    app.kubernetes.io/component: recipevault-frontend
    app.kubernetes.io/instance: recipevault-frontend
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    deployment: recipevault-frontend
status:
  loadBalancer: {}
