apiVersion: v1
data:
  VUE_APP_IMAGE_SERVER_URL: <S3 Public Endpoint>
  VUE_APP_RECIPE_DATA_SERVICE: <REST Recipe Route>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: recipe-vault
  name: recipevault-ui-config
